spring.application.name=springbase
server.port=1890

# Database Configuration (H2 in Postgres Mode)
spring.datasource.url=jdbc:h2:mem:springbase;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Security Configuration
spring.security.user.name=admin
spring.security.user.password=admin

# Cache Configuration
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterAccess=600s

# Logging
logging.level.org.springframework.security=INFO
logging.level.com.jauharxlr.springbase=DEBUG

# Springbase Security Keys
springbase.anon-key=sb_anon_key_shared_test
springbase.service-role-key=sb_service_role_key_admin_test
